services:
  - type: worker
    name: ebooks-telegram-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python getbotbook.py"
    envVars:
      - key: API_TOKEN
        sync: false    # set manually in Render Dashboard
      - key: ADMIN_ID
        sync: false    # set manually in Render Dashboard
      - key: SPECIAL_PIN
        value: "2762"  # default, override if needed
      - key: DATABASE_URL
        fromDatabase:
          name: ebooks-db
          property: connectionString

databases:
  - name: ebooks-db
    plan: free
    
